### ISSUE TITLE
Error to start plugin

### ISSUE THREAD

**Issue by tanabay27** [bartocc/homebridge-flipr#4]
**Describe The Bug:**

7/21/2024, 3:35:37 PM] [Piscine - Salleboeuf] Successfully authenticated on Flipr API:
[7/21/2024, 3:35:37 PM] [homebridge-tydom] Launched child bridge with PID 6073
[7/21/2024, 3:35:37 PM] [Piscine - Salleboeuf] discovered module D36640
[7/21/2024, 3:35:37 PM] [Piscine - Salleboeuf] Restoring existing accessory from cache: D36640
[7/21/2024, 3:35:37 PM] [Piscine - Salleboeuf] discovered module G1859A3E
[7/21/2024, 3:35:37 PM] [Piscine - Salleboeuf] Restoring existing accessory from cache: G1859A3E
[7/21/2024, 3:35:37 PM] [Piscine - Salleboeuf] discovered module F313BC7C
[7/21/2024, 3:35:37 PM] [Piscine - Salleboeuf] Restoring existing accessory from cache: F313BC7C
[7/21/2024, 3:35:37 PM] TypeError: Cannot read properties of null (reading 'Temperature')
    at FliprPlatformAccessory.fetchLastSurvey (/var/lib/homebridge/node_modules/homebridge-flipr/src/platformAccessory.ts:71:14)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[7/21/2024, 3:35:37 PM] TypeError: Cannot read properties of null (reading 'Temperature')
    at FliprPlatformAccessory.fetchLastSurvey (/var/lib/homebridge/node_modules/homebridge-flipr/src/platformAccessory.ts:71:14)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[7/21/2024, 3:35:37 PM] Got SIGTERM, shutting down Homebridge...

**To Reproduce:**

**Expected behavior:**

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**: 0.1.4
* **Homebridge Version**:  1.8.4
* **Node.js Version**:  20.15.1
* **NPM Version**: 
* **Operating System**:  Ubuntu

**Comment by bartocc** [comment]
Sorry, this project is not maintained anymore
